name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  luacheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Run LuaCheck
        uses: lunarmodules/luacheck@cc089e3f65acdd1ef8716cc73a3eca24a6b845e4 # v1.2.0

  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Run Prettier
        run: npx --yes prettier --check .

  stylua:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Run Stylua
        uses: JohnnyMorganz/stylua-action@b6661824b86c9c33121bed87a778b660ba90cf77 # v4.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.20.0
          args: --check .

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Install gettext and Neovim
        run: sudo apt-get install -y gettext neovim

      - name: Clone Plenary
        run: git clone https://github.com/nvim-lua/plenary.nvim

      - name: env
        run: |
          pwd
          ls

      - name: Create `init.vim`
        run: |
          mkdir -p $HOME/.config/nvim
          printf "lua vim.opt.rtp:append('$HOME/plenary.nvim') \n \
                  source $HOME/plenary.nvim/plugin/plenary.vim" > $HOME/.config/nvim/init.vim

      - name: Print `init.vim`
        run: cat $HOME/.config/nvim/init.vim

      - name: Run tests
        run: nvim --headless -c "PlenaryBustedDirectory test/"
