name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  luacheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Run LuaCheck
        uses: lunarmodules/luacheck@cc089e3f65acdd1ef8716cc73a3eca24a6b845e4 # v1.2.0

  msgfmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install gettext
        run: sudo apt-get install -y gettext

      - name: Run msgfmt
        run: find . -name '*.po' -exec msgfmt --check --output-file=/dev/null {} \;

  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Run Prettier
        run: npx --yes prettier --check .

  stylua:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Run Stylua
        uses: JohnnyMorganz/stylua-action@479972f01e665acfcba96ada452c36608bdbbb5e # v4.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.20.0
          args: --check .

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        neovim: [v0.10.1, v0.10.2]

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

        # Appimage requires libfuse2.
      - name: Install gettext and libfuse2
        run: sudo apt-get install -y gettext libfuse2

        # We download Neovim from the GitHub releases page as the version in
        # the Ubuntu repositories is outdated.
      - name: Download Neovim
        run: |
          wget https://github.com/neovim/neovim/releases/download/${{ matrix.neovim }}/nvim.appimage -O $HOME/nvim.appimage
          chmod +x $HOME/nvim.appimage

      - name: Clone Plenary
        run: git clone https://github.com/nvim-lua/plenary.nvim $HOME/plenary.nvim

      - name: Create `init.vim`
        run: |
          mkdir -p $HOME/.config/nvim
          printf "lua vim.opt.rtp:append('$HOME/plenary.nvim') \n \
                  source $HOME/plenary.nvim/plugin/plenary.vim" > $HOME/.config/nvim/init.vim

      - name: Run tests
        run: $HOME/nvim.appimage --headless -c "PlenaryBustedDirectory test/"

  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Type check
        uses: mrcjkb/lua-typecheck-action@a0294260025e6aee0e5777b9f87236ecede98c11 # v1.0.0
        with:
          checklevel: Hint
